import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import morgan from 'morgan';
import productRoutes from './routes/products.js';
import orderRoutes from './routes/orders.js';
import paymentRoutes from './routes/payments.js';
import adminRoutes from './routes/admin.js';
import contentRoutes from './routes/content.js';
import authRoutes from './routes/authRoutes.js';
import userRoutes from './routes/userRoutes.js';

const app = express();
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const frontendDir = path.resolve(__dirname, '../../frontend');
const origins = String(process.env.CLIENT_URL || '').split(',').map(x=>x.trim()).filter(Boolean);

app.set('trust proxy',1);
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(compression());
app.use(cookieParser());
app.use(cors({origin:(origin,cb)=>!origin||!origins.length||origins.includes(origin)?cb(null,true):cb(new Error('CORS origin not allowed')),credentials:true}));
app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
app.use(express.json({limit:'8mb'}));
app.use(express.urlencoded({extended:true}));
app.use(morgan(process.env.NODE_ENV==='production'?'combined':'dev'));
app.get('/api/health',(_req,res)=>res.json({success:true,name:'AURØGANT API',status:'running',time:new Date().toISOString()}));
app.use('/api/products',productRoutes);
app.use('/api/orders',orderRoutes);
app.use('/api/payments',paymentRoutes);
app.use('/api/admin',adminRoutes);
app.use('/api/content',contentRoutes);
app.use(express.static(frontendDir));
app.use((req,res)=>req.path.startsWith('/api/')?res.status(404).json({success:false,message:'Route not found'}):res.sendFile(path.join(frontendDir,'index.html')));
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({success:false,message:'Server error'});});
export default app;