import express from 'express';
import crypto from 'crypto';
import Order from '../models/Order.js';
import Design from '../models/Design.js';
import { protect } from '../middleware/authMiddleware.js';
import { createOrder, findOrder, updateOrder } from '../utils/store.js';

const router=express.Router();
const PRICES={UH62:999,UA30:799,UA26:749,FC32:449,UH38:899,UH83:1099,UH32:799,UH35:899,UH26:699,UJ31:1299,UC61:549,UA22:499,UB73:699,UC21:395,MP25:599,UC28:799,UR37:449,UR50:499,UR39:449,UC23:699,UT58:599,UV34:449};
const GST=Number(process.env.GST_RATE||5),FREE=Number(process.env.FREE_SHIPPING_ABOVE||999),SHIPPING=Number(process.env.STANDARD_SHIPPING||99);
const makeId=()=>`AUR-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;
function calculate(items){if(!Array.isArray(items)||!items.length)throw new Error('At least one item is required.');let subtotal=0;const normalized=items.map(raw=>{const code=String(raw.code||'').toUpperCase(),basePrice=PRICES[code];if(!basePrice)throw new Error(`Product not found: ${raw.code}`);const quantity=Math.max(1,Math.min(100,Number(raw.quantity)||1)),objects=Math.max(0,Math.min(20,Number(raw.designObjectCount)||0)),print=objects?99+25*Math.max(0,objects-1):0,price=basePrice+print;subtotal+=price*quantity;return{...raw,code,name:String(raw.name||code),basePrice,unitPrice:price,price,printCharge:print,quantity};});const shipping=subtotal>=FREE?0:SHIPPING,gst=Math.round(subtotal*GST/100);return{items:normalized,totals:{subtotal,shipping,gst,total:subtotal+shipping+gst}}}
async function persist(order){if(process.env.MONGODB_URI){try{return await Order.create(order)}catch(e){console.error('Mongo order write failed:',e.message);}}return createOrder(order)}
router.post('/',async(req,res)=>{try{const{customer,paymentMethod='cod'}=req.body;if(!customer?.name||!customer?.phone||!customer?.address)return res.status(400).json({success:false,message:'Customer details are incomplete.'});if(!['cod','online'].includes(paymentMethod))return res.status(400).json({success:false,message:'Invalid payment method.'});const calculated=calculate(req.body.items),order={orderNumber:makeId(),user:req.user?._id||null,customer,items:calculated.items,totals:calculated.totals,paymentMethod,paymentStatus:'pending',status:paymentMethod==='cod'?'confirmed':'payment_pending',razorpayOrderId:'',razorpayPaymentId:'',tracking:{}};const saved=await persist(order); if(process.env.MONGODB_URI){for(const item of calculated.items.filter(x=>x.designId)){await Design.updateOne({designId:item.designId},{$set:{orderNumber:order.orderNumber,status:'ordered',user:req.user?._id||null}})}} res.status(201).json({success:true,order:saved.toObject?saved.toObject():saved});}catch(e){res.status(400).json({success:false,message:e.message||'Unable to create order.'})}});
router.get('/mine',protect,async(req,res)=>{if(!process.env.MONGODB_URI)return res.json({success:true,orders:[]});const orders=await Order.find({user:req.user._id}).sort({createdAt:-1}).lean();res.json({success:true,orders})});
router.get('/:id',async(req,res)=>{if(process.env.MONGODB_URI){const order=await Order.findOne({$or:[{orderNumber:req.params.id},{razorpayOrderId:req.params.id}]}).lean();if(!order)return res.status(404).json({success:false,message:'Order not found'});return res.json({success:true,order})}const order=await findOrder(req.params.id);if(!order)return res.status(404).json({success:false,message:'Order not found'});res.json({success:true,order})});
export{calculate};export default router;