let studio={product:null,color:null,size:null,quantity:1,canvas:null};
function loadStudioProduct(){const code=new URLSearchParams(location.search).get('id')||localStorage.getItem('selectedProductCode')||'UC21';studio.product=selectedProduct(code)||window.AUR_PRODUCTS[0];studio.color=studio.product.colors?.[0]||'Black';studio.size=studio.product.sizes?.[0]||'M';
 document.getElementById('studioName').textContent=studio.product.name;document.getElementById('studioCode').textContent=studio.product.code;document.getElementById('studioBase').textContent=money(studio.product.salePrice||studio.product.price);document.getElementById('studioMockup').src=productImage(studio.product);
 document.getElementById('studioColor').innerHTML=(studio.product.colors||[]).map(c=>`<button class="chip ${c===studio.color?'active':''}" data-color="${esc(c)}">${esc(c)}</button>`).join('');document.getElementById('studioSize').innerHTML=(studio.product.sizes||[]).map(s=>`<option>${esc(s)}</option>`).join('');
 document.getElementById('studioColor').querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{studio.color=b.dataset.color;document.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('active',x.dataset.color===studio.color));});
 document.getElementById('studioSize').value=studio.size;document.getElementById('studioSize').onchange=e=>studio.size=e.target.value;document.getElementById('studioQty').oninput=e=>studio.quantity=Math.max(1,Number(e.target.value)||1);
 initCanvas();renderStudioProducts();updateStudioPrice();
}
function initCanvas(){const canvasEl=document.getElementById('designCanvas');studio.canvas=new fabric.Canvas(canvasEl,{preserveObjectStacking:true});studio.canvas.setWidth(520);studio.canvas.setHeight(620);fabric.Image.fromURL(productImage(studio.product),img=>{img.set({left:260,top:310,originX:'center',originY:'center',scaleX:Math.min(500/img.width,590/img.height)});img.selectable=false;img.evented=false;img.name='mockup';studio.canvas.setBackgroundImage(img,studio.canvas.renderAll.bind(studio.canvas));});
 document.getElementById('addText').onclick=()=>{const t=new fabric.IText('YOUR DESIGN',{left:260,top:300,originX:'center',fill:'#111',fontSize:36,fontFamily:'Arial',fontWeight:'700'});studio.canvas.add(t).setActiveObject(t);updateStudioPrice()};
 document.getElementById('uploadArt').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=ev=>fabric.Image.fromURL(ev.target.result,img=>{img.scaleToWidth(150);img.set({left:260,top:300,originX:'center'});studio.canvas.add(img).setActiveObject(img);updateStudioPrice()});r.readAsDataURL(file)};
 document.getElementById('clearCanvas').onclick=()=>{studio.canvas.getObjects().filter(o=>o.name!=='mockup').forEach(o=>studio.canvas.remove(o));updateStudioPrice()};document.getElementById('exportCanvas').onclick=()=>{const a=document.createElement('a');a.href=studio.canvas.toDataURL({format:'png',multiplier:2});a.download=`${studio.product.code}-design.png`;a.click()};
 studio.canvas.on('object:added',updateStudioPrice);studio.canvas.on('object:removed',updateStudioPrice);studio.canvas.on('object:modified',updateStudioPrice);
}
function updateStudioPrice(){if(!studio.product)return;const objs=studio.canvas?studio.canvas.getObjects().filter(o=>o.name!=='mockup'):[];let print=objs.length?99:0;if(objs.length>1)print+=25*(objs.length-1);const qty=studio.quantity||1;const subtotal=(studio.product.salePrice||studio.product.price)+print;const discount=qty>=10?Math.round(subtotal*.1):qty>=5?Math.round(subtotal*.05):0;const total=Math.max(0,(subtotal-discount)*qty);document.getElementById('studioPrint').textContent=money(print);document.getElementById('studioDiscount').textContent=money(discount*qty);document.getElementById('studioTotal').textContent=money(total);}
function renderStudioProducts(){const list=document.getElementById('studioProducts');list.innerHTML=window.AUR_PRODUCTS.map(p=>`<button class="studio-product" data-code="${p.code}"><img src="${productImage(p)}"><span><strong>${esc(p.name)}</strong><small>${p.code} · ${money(p.salePrice||p.price)}</small></span></button>`).join('');list.querySelectorAll('[data-code]').forEach(b=>b.onclick=()=>{localStorage.setItem('selectedProductCode',b.dataset.code);location.href=`studio.html?id=${b.dataset.code}`})}
function addStudioToCart(){const objs=studio.canvas.getObjects().filter(o=>o.name!=='mockup');const preview=studio.canvas.toDataURL({format:'png'});const print=objs.length?99+25*Math.max(0,objs.length-1):0;const unit=(studio.product.salePrice||studio.product.price)+print;const designId=`D-${Date.now()}`;localStorage.setItem(`aur_design_${designId}`,preview);addToCart({code:studio.product.code,name:studio.product.name,productImage:productImage(studio.product),size:studio.size,color:studio.color,unitPrice:unit,quantity:studio.quantity,designId,preview});location.href='cart.html'}
document.addEventListener('DOMContentLoaded',()=>{if(document.getElementById('designCanvas')){loadStudioProduct();document.getElementById('addStudioCart').onclick=addStudioToCart}});
